import type {
  User,
  Module,
  Event,
  Assignment,
  Assessment,
  StudySession,
} from "./types";

export const user: User = {
  id: "user-1",
  name: "Alex Carter",
  email: "alex.carter@law.school.edu",
  academicYear: "2L",
  timezone: "America/Chicago",
};

export const modules: Module[] = [
  {
    id: "mod-conlaw",
    name: "Constitutional Law",
    lecturerName: "Prof. Helena Carter",
    color: "#050505",
    icon: "scale",
    notes: "Monday and Wednesday lectures, case-heavy reading load.",
  },
  {
    id: "mod-contracts",
    name: "Contract Law",
    lecturerName: "Prof. David Osei",
    color: "#C8A24A",
    icon: "file-text",
    notes: "Focus on offer, acceptance, and consideration this term.",
  },
  {
    id: "mod-criminal",
    name: "Criminal Law",
    lecturerName: "Prof. Sarah Nkosi",
    color: "#F3C6BD",
    icon: "shield",
    notes: "Problem-question heavy. Practice applying actus reus and mens rea.",
  },
  {
    id: "mod-skills",
    name: "Legal Skills",
    lecturerName: "Prof. Michael Tran",
    color: "#CAD2C5",
    icon: "book-open",
    notes: "Covers legal writing, research, and advocacy. Weekly writing tasks.",
  },
  {
    id: "mod-research",
    name: "Legal Research",
    lecturerName: "Prof. Amina Yusuf",
    color: "#EFE7D0",
    icon: "search",
    notes: "Library and database skills. Research essay due end of term.",
  },
];

export const events: Event[] = [
  {
    id: "evt-1",
    title: "Constitutional Law — Lecture",
    type: "class",
    moduleId: "mod-conlaw",
    date: "2026-05-04",
    startTime: "09:00",
    endTime: "11:00",
    location: "Room 201, Law Building",
    priority: "medium",
    reminder: 15,
  },
  {
    id: "evt-2",
    title: "Contract Law — Tutorial",
    type: "class",
    moduleId: "mod-contracts",
    date: "2026-05-04",
    startTime: "14:00",
    endTime: "15:00",
    location: "Room 104, Law Building",
    priority: "medium",
    reminder: 10,
  },
  {
    id: "evt-3",
    title: "Library Reading Block",
    type: "reading",
    moduleId: "mod-conlaw",
    date: "2026-05-05",
    startTime: "10:00",
    endTime: "13:00",
    location: "Law Library — Floor 2",
    priority: "low",
  },
  {
    id: "evt-4",
    title: "Criminal Law — Study Group",
    type: "study-session",
    moduleId: "mod-criminal",
    date: "2026-05-06",
    startTime: "15:00",
    endTime: "17:00",
    location: "Cafe Nero",
    priority: "high",
    notes: "Work through problem-question set 3 together.",
    reminder: 30,
  },
  {
    id: "evt-5",
    title: "Legal Skills — Writing Workshop",
    type: "class",
    moduleId: "mod-skills",
    date: "2026-05-07",
    startTime: "11:00",
    endTime: "13:00",
    location: "Room 305, Law Building",
    priority: "medium",
  },
  {
    id: "evt-6",
    title: "Personal — Gym",
    type: "personal",
    date: "2026-05-05",
    startTime: "07:00",
    endTime: "08:00",
    location: "University Sports Centre",
    priority: "low",
  },
];

export const assignments: Assignment[] = [
  {
    id: "asgn-1",
    title: "Contract Law — Offer & Acceptance Essay",
    moduleId: "mod-contracts",
    description: "Analyse the postal rule and its application in modern contract formation.",
    dueDate: "2026-05-18",
    status: "in-progress",
    priority: "high",
    estimatedHours: 12,
    progress: 35,
    notes: "Focus on Adams v Lindsell and electronic communications.",
  },
  {
    id: "asgn-2",
    title: "Legal Research — Annotated Bibliography",
    moduleId: "mod-research",
    description: "Compile and annotate 10 sources on judicial precedent.",
    dueDate: "2026-05-25",
    status: "not-started",
    priority: "medium",
    estimatedHours: 8,
    progress: 0,
  },
  {
    id: "asgn-3",
    title: "Criminal Law — Problem Question 2",
    moduleId: "mod-criminal",
    description: "Apply actus reus and mens rea to the given scenario.",
    dueDate: "2026-05-11",
    status: "in-progress",
    priority: "high",
    estimatedHours: 6,
    progress: 50,
  },
  {
    id: "asgn-4",
    title: "Constitutional Law — Judicial Review Essay",
    moduleId: "mod-conlaw",
    description: "Critically evaluate the grounds for judicial review.",
    dueDate: "2026-05-30",
    status: "not-started",
    priority: "medium",
    estimatedHours: 15,
    progress: 0,
    notes: "Focus on irrationality and proportionality post-GCHQ.",
  },
];

export const assessments: Assessment[] = [
  {
    id: "asmt-1",
    title: "Criminal Law — Mid-Term Test",
    moduleId: "mod-criminal",
    assessmentType: "test",
    date: "2026-05-15",
    topics: ["Actus Reus", "Mens Rea", "Strict Liability"],
    confidenceLevel: 3,
    priority: "high",
    notes: "Multiple choice and short-answer format.",
  },
  {
    id: "asmt-2",
    title: "Contract Law — Formative Test",
    moduleId: "mod-contracts",
    assessmentType: "test",
    date: "2026-05-22",
    topics: ["Offer", "Acceptance", "Consideration", "Intention to Create Legal Relations"],
    confidenceLevel: 4,
    priority: "medium",
  },
  {
    id: "asmt-3",
    title: "Constitutional Law — Final Exam",
    moduleId: "mod-conlaw",
    assessmentType: "exam",
    date: "2026-06-10",
    topics: ["Judicial Review", "Separation of Powers", "Parliamentary Sovereignty", "Human Rights Act"],
    confidenceLevel: 2,
    priority: "high",
    notes: "Three-hour closed-book exam. Essay and problem-question format.",
  },
];

export const studySessions: StudySession[] = [
  {
    id: "ss-1",
    title: "Constitutional Law — Case Review",
    moduleId: "mod-conlaw",
    linkedAssignmentId: "asgn-4",
    date: "2026-05-06",
    startTime: "14:00",
    endTime: "16:00",
    goal: "Read and brief 5 key judicial review cases.",
    status: "planned",
  },
  {
    id: "ss-2",
    title: "Criminal Law — Problem Question Practice",
    moduleId: "mod-criminal",
    linkedAssessmentId: "asmt-1",
    date: "2026-05-08",
    startTime: "10:00",
    endTime: "12:00",
    goal: "Complete 3 practice questions under timed conditions.",
    status: "planned",
  },
  {
    id: "ss-3",
    title: "Contract Law — Consideration Recap",
    moduleId: "mod-contracts",
    date: "2026-05-03",
    startTime: "16:00",
    endTime: "18:00",
    goal: "Review lecture notes and create a consideration flowchart.",
    status: "completed",
    reflectionNotes: "Feeling stronger on the topic. Need to revisit promissory estoppel.",
  },
];
