import type {
  User,
  Module,
  Event,
  Assignment,
  Assessment,
  StudySession,
  Note,
} from "./types";

export const user: User = {
  id: "user-1",
  name: "Alex Carter",
  email: "alex.carter@law.school.edu",
  academicYear: "2L",
  timezone: "America/Chicago",
};

export const modules: Module[] = [
  {
    id: "mod-conlaw",
    name: "Constitutional Law",
    lecturerName: "Prof. Helena Carter",
    color: "#050505",
    icon: "scale",
    notes: "Monday and Wednesday lectures, case-heavy reading load.",
  },
  {
    id: "mod-contracts",
    name: "Contract Law",
    lecturerName: "Prof. David Osei",
    color: "#C8A24A",
    icon: "file-text",
    notes: "Focus on offer, acceptance, and consideration this term.",
  },
  {
    id: "mod-criminal",
    name: "Criminal Law",
    lecturerName: "Prof. Sarah Nkosi",
    color: "#F3C6BD",
    icon: "shield",
    notes: "Problem-question heavy. Practice applying actus reus and mens rea.",
  },
  {
    id: "mod-skills",
    name: "Legal Skills",
    lecturerName: "Prof. Michael Tran",
    color: "#CAD2C5",
    icon: "book-open",
    notes: "Covers legal writing, research, and advocacy. Weekly writing tasks.",
  },
  {
    id: "mod-research",
    name: "Legal Research",
    lecturerName: "Prof. Amina Yusuf",
    color: "#EFE7D0",
    icon: "search",
    notes: "Library and database skills. Research essay due end of term.",
  },
];

export const events: Event[] = [
  {
    id: "evt-1",
    title: "Constitutional Law — Lecture",
    type: "class",
    moduleId: "mod-conlaw",
    date: "2026-05-04",
    startTime: "09:00",
    endTime: "11:00",
    location: "Room 201, Law Building",
    priority: "medium",
    reminder: 15,
  },
  {
    id: "evt-2",
    title: "Contract Law — Tutorial",
    type: "class",
    moduleId: "mod-contracts",
    date: "2026-05-04",
    startTime: "14:00",
    endTime: "15:00",
    location: "Room 104, Law Building",
    priority: "medium",
    reminder: 10,
  },
  {
    id: "evt-3",
    title: "Library Reading Block",
    type: "reading",
    moduleId: "mod-conlaw",
    date: "2026-05-05",
    startTime: "10:00",
    endTime: "13:00",
    location: "Law Library — Floor 2",
    priority: "low",
  },
  {
    id: "evt-4",
    title: "Criminal Law — Study Group",
    type: "study-session",
    moduleId: "mod-criminal",
    date: "2026-05-06",
    startTime: "15:00",
    endTime: "17:00",
    location: "Cafe Nero",
    priority: "high",
    notes: "Work through problem-question set 3 together.",
    reminder: 30,
  },
  {
    id: "evt-5",
    title: "Legal Skills — Writing Workshop",
    type: "class",
    moduleId: "mod-skills",
    date: "2026-05-07",
    startTime: "11:00",
    endTime: "13:00",
    location: "Room 305, Law Building",
    priority: "medium",
  },
  {
    id: "evt-6",
    title: "Personal — Gym",
    type: "personal",
    date: "2026-05-05",
    startTime: "07:00",
    endTime: "08:00",
    location: "University Sports Centre",
    priority: "low",
  },
];

export const assignments: Assignment[] = [
  {
    id: "asgn-1",
    title: "Contract Law — Offer & Acceptance Essay",
    moduleId: "mod-contracts",
    description: "Analyse the postal rule and its application in modern contract formation.",
    dueDate: "2026-05-18",
    status: "in-progress",
    priority: "high",
    estimatedHours: 12,
    progress: 35,
    notes: "Focus on Adams v Lindsell and electronic communications.",
  },
  {
    id: "asgn-2",
    title: "Legal Research — Annotated Bibliography",
    moduleId: "mod-research",
    description: "Compile and annotate 10 sources on judicial precedent.",
    dueDate: "2026-05-25",
    status: "not-started",
    priority: "medium",
    estimatedHours: 8,
    progress: 0,
  },
  {
    id: "asgn-3",
    title: "Criminal Law — Problem Question 2",
    moduleId: "mod-criminal",
    description: "Apply actus reus and mens rea to the given scenario.",
    dueDate: "2026-05-11",
    status: "in-progress",
    priority: "high",
    estimatedHours: 6,
    progress: 50,
  },
  {
    id: "asgn-4",
    title: "Constitutional Law — Judicial Review Essay",
    moduleId: "mod-conlaw",
    description: "Critically evaluate the grounds for judicial review.",
    dueDate: "2026-05-30",
    status: "not-started",
    priority: "medium",
    estimatedHours: 15,
    progress: 0,
    notes: "Focus on irrationality and proportionality post-GCHQ.",
  },
];

export const assessments: Assessment[] = [
  {
    id: "asmt-1",
    title: "Criminal Law — Mid-Term Test",
    moduleId: "mod-criminal",
    assessmentType: "test",
    date: "2026-05-15",
    topics: ["Actus Reus", "Mens Rea", "Strict Liability"],
    confidenceLevel: 3,
    priority: "high",
    notes: "Multiple choice and short-answer format.",
  },
  {
    id: "asmt-2",
    title: "Contract Law — Formative Test",
    moduleId: "mod-contracts",
    assessmentType: "test",
    date: "2026-05-22",
    topics: ["Offer", "Acceptance", "Consideration", "Intention to Create Legal Relations"],
    confidenceLevel: 4,
    priority: "medium",
  },
  {
    id: "asmt-3",
    title: "Constitutional Law — Final Exam",
    moduleId: "mod-conlaw",
    assessmentType: "exam",
    date: "2026-06-10",
    topics: ["Judicial Review", "Separation of Powers", "Parliamentary Sovereignty", "Human Rights Act"],
    confidenceLevel: 2,
    priority: "high",
    notes: "Three-hour closed-book exam. Essay and problem-question format.",
  },
];

export const studySessions: StudySession[] = [
  {
    id: "ss-1",
    title: "Constitutional Law — Case Review",
    moduleId: "mod-conlaw",
    linkedAssignmentId: "asgn-4",
    date: "2026-05-06",
    startTime: "14:00",
    endTime: "16:00",
    goal: "Read and brief 5 key judicial review cases.",
    status: "planned",
  },
  {
    id: "ss-2",
    title: "Criminal Law — Problem Question Practice",
    moduleId: "mod-criminal",
    linkedAssessmentId: "asmt-1",
    date: "2026-05-08",
    startTime: "10:00",
    endTime: "12:00",
    goal: "Complete 3 practice questions under timed conditions.",
    status: "planned",
  },
  {
    id: "ss-3",
    title: "Contract Law — Consideration Recap",
    moduleId: "mod-contracts",
    date: "2026-05-03",
    startTime: "16:00",
    endTime: "18:00",
    goal: "Review lecture notes and create a consideration flowchart.",
    status: "completed",
    reflectionNotes: "Feeling stronger on the topic. Need to revisit promissory estoppel.",
  },
];

export const notes: Note[] = [
  {
    id: "note-1",
    title: "Judicial Review — Key Grounds",
    moduleId: "mod-conlaw",
    content:
      "Illegality — ultra vires, improper purpose, relevant/irrelevant considerations.\nProcedural impropriety — natural justice, duty to consult, bias.\nIrrationality — Wednesbury unreasonableness.\nProportionality — Human Rights Act s.6, GCHQ.\nLegitimate expectation — procedural vs substantive.",
    createdAt: "2026-04-28",
    updatedAt: "2026-05-02",
    tags: ["judicial-review", "key-concepts", "exam"],
  },
  {
    id: "note-2",
    title: "Offer & Acceptance — Flowchart",
    moduleId: "mod-contracts",
    content:
      "1. Is there an offer?\n  - Invitation to treat vs offer (Fisher v Bell, P/SG v Boots)\n  - Unilateral vs bilateral\n2. Was the offer accepted?\n  - Mirror image rule\n  - Postal rule (Adams v Lindsell)\n  - Electronic communications\n3. Was acceptance communicated?\n  - Silence is not acceptance (Felthouse v Bindley)",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-03",
    tags: ["offer-acceptance", "flowchart", "exam"],
  },
  {
    id: "note-3",
    title: "Actus Reus & Mens Rea Summary",
    moduleId: "mod-criminal",
    content:
      "Actus Reus:\n- Conduct, circumstance, result\n- Omissions — only liable if duty exists (statutory, contractual, relationship, assumption of care, creation of danger)\n- Causation — factual (but-for) and legal (operating and substantial cause)\n\nMens Rea:\n- Intention — direct vs oblique (Woollin)\n- Recklessness — Cunningham subjective\n- Negligence — objective standard\n- Strict liability offences — no MR required",
    createdAt: "2026-04-20",
    updatedAt: "2026-04-30",
    tags: ["actus-reus", "mens-rea", "core-principles"],
  },
  {
    id: "note-4",
    title: "Contract — Consideration Cheatsheet",
    moduleId: "mod-contracts",
    content:
      "Definition: Currie v Misa — benefit/detriment.\nRules:\n- Must be sufficient but need not be adequate (Chappell v Nestle)\n- Past consideration is not valid (Re McArdle)\n- Performance of existing duty (Stilk v Myrick, Williams v Roffey Bros)\n- Part-payment of debt (Pinnel's Case, Foakes v Beer)\nPromissory estoppel: Central London Property Trust v High Trees House.",
    createdAt: "2026-04-25",
    updatedAt: "2026-04-25",
    tags: ["consideration", "cheatsheet"],
  },
  {
    id: "note-5",
    title: "Legal Research — Source Hierarchy",
    moduleId: "mod-research",
    content:
      "Primary sources:\n1. Legislation (Acts, statutory instruments)\n2. Case law (law reports, transcripts)\n\nSecondary sources:\n1. Textbooks and practitioner works\n2. Journal articles (LQR, MLR, CLJ)\n3. Halsbury's Laws of England\n4. Hansard (limited use — Pepper v Hart)\n\nDatabases: Westlaw, LexisNexis, BAILII, HeinOnline.",
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    tags: ["research", "sources", "methodology"],
  },
  {
    id: "note-6",
    title: "Parliamentary Sovereignty — Dicey",
    moduleId: "mod-conlaw",
    content:
      "Dicey's three principles:\n1. Parliament can make or unmake any law\n2. No person or body can override Parliament\n3. No Parliament can bind its successors\n\nChallenges:\n- EU membership (Factortame)\n- HRA 1998 s.3-4 (declarations of incompatibility)\n- Devolution (Scotland Act)\n- Common law constitutionalism (Jackson v AG)",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    tags: ["parliamentary-sovereignty", "dicey", "exam"],
  },
];
